//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Starward.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Starward.Core.Localization.CoreLang", typeof(CoreLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse the warp record URL..
        /// </summary>
        internal static string Gacha_CannotParseTheWarpRecordURL {
            get {
                return ResourceManager.GetString("Gacha_CannotParseTheWarpRecordURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse the wish record URL..
        /// </summary>
        internal static string Gacha_CannotParseTheWishRecordURL {
            get {
                return ResourceManager.GetString("Gacha_CannotParseTheWishRecordURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Event Warp.
        /// </summary>
        internal static string GachaType_CharacterEventWarp {
            get {
                return ResourceManager.GetString("GachaType_CharacterEventWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Event Wish.
        /// </summary>
        internal static string GachaType_CharacterEventWish {
            get {
                return ResourceManager.GetString("GachaType_CharacterEventWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Event Wish - 2.
        /// </summary>
        internal static string GachaType_CharacterEventWish_2 {
            get {
                return ResourceManager.GetString("GachaType_CharacterEventWish_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Warp.
        /// </summary>
        internal static string GachaType_DepartureWarp {
            get {
                return ResourceManager.GetString("GachaType_DepartureWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Cone Event Warp.
        /// </summary>
        internal static string GachaType_LightConeEventWarp {
            get {
                return ResourceManager.GetString("GachaType_LightConeEventWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novice Wish.
        /// </summary>
        internal static string GachaType_NoviceWish {
            get {
                return ResourceManager.GetString("GachaType_NoviceWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Wish.
        /// </summary>
        internal static string GachaType_PermanentWish {
            get {
                return ResourceManager.GetString("GachaType_PermanentWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stellar Warp.
        /// </summary>
        internal static string GachaType_StellarWarp {
            get {
                return ResourceManager.GetString("GachaType_StellarWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Event Wish.
        /// </summary>
        internal static string GachaType_WeaponEventWish {
            get {
                return ResourceManager.GetString("GachaType_WeaponEventWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genshin Impact.
        /// </summary>
        internal static string Game_GenshinImpact {
            get {
                return ResourceManager.GetString("Game_GenshinImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honkai Impact 3rd.
        /// </summary>
        internal static string Game_HonkaiImpact3rd {
            get {
                return ResourceManager.GetString("Game_HonkaiImpact3rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honkai: Star Rail.
        /// </summary>
        internal static string Game_HonkaiStarRail {
            get {
                return ResourceManager.GetString("Game_HonkaiStarRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zenless Zone Zero.
        /// </summary>
        internal static string Game_ZZZ {
            get {
                return ResourceManager.GetString("Game_ZZZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Cloud Server.
        /// </summary>
        internal static string GameServer_ChinaCloudServer {
            get {
                return ResourceManager.GetString("GameServer_ChinaCloudServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Server.
        /// </summary>
        internal static string GameServer_ChinaServer {
            get {
                return ResourceManager.GetString("GameServer_ChinaServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe &amp; Americas Servers.
        /// </summary>
        internal static string GameServer_EuropeAmericasServers {
            get {
                return ResourceManager.GetString("GameServer_EuropeAmericasServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Server.
        /// </summary>
        internal static string GameServer_GlobalServer {
            get {
                return ResourceManager.GetString("GameServer_GlobalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan Server.
        /// </summary>
        internal static string GameServer_JapanServer {
            get {
                return ResourceManager.GetString("GameServer_JapanServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea Server.
        /// </summary>
        internal static string GameServer_KoreaServer {
            get {
                return ResourceManager.GetString("GameServer_KoreaServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southeast Asia Server.
        /// </summary>
        internal static string GameServer_SEAServer {
            get {
                return ResourceManager.GetString("GameServer_SEAServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional Chinese Server.
        /// </summary>
        internal static string GameServer_TraditionalChineseServer {
            get {
                return ResourceManager.GetString("GameServer_TraditionalChineseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifacts.
        /// </summary>
        internal static string GenshinQueryType_Artifact {
            get {
                return ResourceManager.GetString("GenshinQueryType_Artifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genesis Crystals.
        /// </summary>
        internal static string GenshinQueryType_GenesisCrystal {
            get {
                return ResourceManager.GetString("GenshinQueryType_GenesisCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Resins.
        /// </summary>
        internal static string GenshinQueryType_OriginalResin {
            get {
                return ResourceManager.GetString("GenshinQueryType_OriginalResin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primogems.
        /// </summary>
        internal static string GenshinQueryType_Primogem {
            get {
                return ResourceManager.GetString("GenshinQueryType_Primogem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons.
        /// </summary>
        internal static string GenshinQueryType_Weapon {
            get {
                return ResourceManager.GetString("GenshinQueryType_Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string PostType_Activity {
            get {
                return ResourceManager.GetString("PostType_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notices.
        /// </summary>
        internal static string PostType_Announcement {
            get {
                return ResourceManager.GetString("PostType_Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string PostType_Information {
            get {
                return ResourceManager.GetString("PostType_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Cone.
        /// </summary>
        internal static string StarRailQueryType_LightCone {
            get {
                return ResourceManager.GetString("StarRailQueryType_LightCone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oneiric Shared.
        /// </summary>
        internal static string StarRailQueryType_OneiricShared {
            get {
                return ResourceManager.GetString("StarRailQueryType_OneiricShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relic.
        /// </summary>
        internal static string StarRailQueryType_Relic {
            get {
                return ResourceManager.GetString("StarRailQueryType_Relic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stellar Jade.
        /// </summary>
        internal static string StarRailQueryType_StellarJade {
            get {
                return ResourceManager.GetString("StarRailQueryType_StellarJade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailblaze Power.
        /// </summary>
        internal static string StarRailQueryType_TrailblazePower {
            get {
                return ResourceManager.GetString("StarRailQueryType_TrailblazePower", resourceCulture);
            }
        }
    }
}
